tags:
  - ubuntu-python-nginx
  - ubuntu22.04-python-nginx
  - lts-python-nginx
  - ubuntu-python3.10-nginx
  - poetry1.2.0-nginx
  - lts-poetry1.2.0-nginx
  - ubuntu-python-poetry1.2.0-nginx
  - ubuntu-python3.10-poetry1.2.0-nginx
  - ubuntu22.04-python-poetry1.2.0-nginx
  - ubuntu22.04-python3.10-poetry1.2.0-nginx
